name = "Quickhull"
uuid = "baca2653-9c88-49d2-a488-12dbf25fc4fb"
authors = ["August"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Polyhedra = "67491407-f73d-577b-9b50-8179a7c68029"

[extensions]
QuickhullGeometryBasicsExt = "GeometryBasics"
QuickhullPolyhedraExt = "Polyhedra"
